### ISSUE TITLE
Error when trying to start the Coordinator App on Mac

### ISSUE THREAD

**Issue by vdeparday** [osmlab/field-data-coordinator#113]
![image](https://user-images.githubusercontent.com/1036189/30660651-999815cc-9e0f-11e7-8bad-343214219181.png)

**Comment by dereklieu** [comment]
@vdeparday were you able to get the app working previously? Wondering if this is an issue with the second release.

**Comment by vdeparday** [comment]
It is the first time I try but Cristiano managed to run it before. Let me try rc1

**Comment by vdeparday** [comment]
RC1 does start so it is a problem with RC2

**Comment by vdeparday** [comment]
RC2 is working now. Thanks
