### ISSUE TITLE
Map should zoom to the bounding box of available data

### ISSUE THREAD

**Issue by mojodna** [osmlab/field-data-coordinator#52]
(Data tab)

**Comment by dereklieu** [comment]
This should already be happening, but doesn't always work on some screen sizes for our weird test data. 

Example:

<img width="612" alt="screen shot 2017-07-28 at 2 30 59 pm" src="https://user-images.githubusercontent.com/1590802/28731318-69893fc0-73a1-11e7-8c81-a4199d2081e2.png">

(Map is zoomed all the way out, but the weird aspect ratio, plus the even worldwide distribution of observations, makes fitting everything impossible.)

I think real data that's more geographically localized (ie no observations from both poles) will address this.
