### ISSUE TITLE
Date range doesn't work

### ISSUE THREAD

**Issue by felskia** [osmlab/field-data-coordinator#87]
@dereklieu  you can't select anything different than the dates already provided.

**Comment by dereklieu** [comment]
Seems to work for me. The range is clamped to dates that actually have data, and it's preset to the maximum range, so in effect you can only make the range smaller.

**Comment by felskia** [comment]
Hmmm. This is what it looks like for me: 

<img width="248" alt="screen shot 2017-08-14 at 11 45 33 am" src="https://user-images.githubusercontent.com/5421566/29279542-3178be9c-80e6-11e7-9bac-d34e780b46bc.png">

Maybe I just need a larger date range??

**Comment by dereklieu** [comment]
Oh yeah that means all your observations were loaded on that one day :)

I can show you how to load more observations, which would result in a broader date range.
